version: "2"

services:
  rabbit:
    image: rabbitmq
    environment: 
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
  redis:
    image: redis
    ports:
      - "6379:6379"